import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components/navbar";

const cloisterBlack = localFont({
  src: "./fonts/CloisterBlack.ttf",
  variable: "--font-cloister-black",
});

const lora = localFont({
  src: "./fonts/Lora-VariableFont_wght.ttf",
  variable: "--font-lora",
  weight: "400 500 600 700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lora.variable} ${cloisterBlack.variable} max-w-[1200px] mx-auto`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
